server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://60.205.221.172/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kun3.1415926
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: songyuankun.top
    port: 6379
    password: 123456
  cache:
    type: redis

my:
  wechat:
    appid: wx535bf80f60239064
    secret: 93c631b2be9d60689dad05af5c30cf7d