server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://60.205.221.172/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kun3.1415926
    driver-class-name: com.mysql.cj.jdbc.Driver