server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.31.88:3306/wechat?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: wechat
    password: F7BYz34328RXhWmf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: com.songyuankun.wechat.infrastructure.MysqlConfig
  redis:
    database: 0
    host: 192.168.31.88
    port: 6379
    password: 123456
  cache:
    type: redis
  session:
    store-type: redis
  jackson:
    time-zone: GMT+8
jwt:
  header: Authorization
  expiration: 864000
  tokenHead: Bearer

rocketmq:
  name-server: 192.168.31.88:9876
  producer:
    group: DEFAULT_GROUP

my:
  wechat:
    appid:
    secret:

qiniu:
  ak:
  sk:
  bucket:
  cdn_host:
