server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://60.205.221.172:3306/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Kun3.1415926
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: 60.205.221.172
    port: 6379
    password: 123456
  cache:
    type: redis

  session:
    store-type: redis

# JWT相关配置
jwt:
  header: Authorization
  # 过期时间
  expiration: 864000
  # 注意有一个空格
  tokenHead: Bearer
my:
  wechat:
    appid: wx535bf80f60239064
    secret: 93c631b2be9d60689dad05af5c30cf7d