server:
  port: 8082
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 60.205.221.172:8848
    group: DEFAULT_GROUP
    auto-refresh: true
    type: yaml
    data-id: wechat-api
spring:
  application:
    name: wechat-api
